server:
  port: 8089

spring:
  application:
    name: payment-service
  config:
    import: optional:configserver:http://localhost:8090

#  datasource:
#    url: jdbc:postgresql://localhost:5432/CS_Payment
#    username: postgres
#    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true